export const SET_BEACONS = 'SET_BEACONS';
export const SET_BEACON = 'SET_BEACON';
export const SET_LOGIN_AVAILABLE = 'SET_LOGIN_AVAILABLE';
export const SET_LOGGING_IN = 'SET_LOGGING_IN';
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED';
