export const SET_BEACONS = 'SET_BEACONS';
export const SET_BEACON = 'SET_BEACON';
export const SET_LOGIN_AVAILABLE = 'SET_LOGIN_AVAILABLE';
export const SET_LOGGING_IN = 'SET_LOGGING_IN';
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED';

// 定期的な実行
export const FETCH_CLOCK = 'FETCH_CLOCK';
export const ACCEPT_REQUESTS = 'ACCEPT_REQUESTS';
