export const INIT_STATE = 'INIT_STATE';
export const SET_USER = 'SET_USER';
export const NAVIGATOR_PUSH = 'NAVIGATOR_PUSH';
export const NAVIGATOR_POP = 'NAVIGATOR_POP';
export const SET_REQUESTS = 'SET_REQUESTS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_ACTIVE_REQUEST = 'SET_ACTIVE_REQUEST';
